package com.jobtracker.application;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

/**
 * Business logic for applications. Controllers stay thin and delegate here.
 * <p>
 * Note: not-found is signalled with {@link ResponseStatusException} for now;
 * Phase 1.5 replaces this with a dedicated exception + {@code @RestControllerAdvice}.
 */
@Service
@Transactional
public class ApplicationService {

    private final ApplicationRepository repository;

    public ApplicationService(ApplicationRepository repository) {
        this.repository = repository;
    }

    @Transactional(readOnly = true)
    public Page<Application> list(Pageable pageable) {
        return repository.findAll(pageable);
    }

    @Transactional(readOnly = true)
    public Application get(Long id) {
        return repository.findById(id).orElseThrow(() -> notFound(id));
    }

    public Application create(Application application) {
        // Ids are generated by the database; never trust a client-supplied one.
        application.setId(null);
        return repository.save(application);
    }

    public Application update(Long id, Application data) {
        Application existing = repository.findById(id).orElseThrow(() -> notFound(id));
        existing.setPosition(data.getPosition());
        existing.setStatus(data.getStatus());
        existing.setSourceUrl(data.getSourceUrl());
        existing.setSalaryMin(data.getSalaryMin());
        existing.setSalaryMax(data.getSalaryMax());
        existing.setAppliedAt(data.getAppliedAt());
        existing.setDeadline(data.getDeadline());
        existing.setTechStack(data.getTechStack());
        return existing; // flushed on commit (managed entity)
    }

    public void delete(Long id) {
        if (!repository.existsById(id)) {
            throw notFound(id);
        }
        repository.deleteById(id);
    }

    private ResponseStatusException notFound(Long id) {
        return new ResponseStatusException(HttpStatus.NOT_FOUND, "Application not found: " + id);
    }
}
